# Generated by Django 4.0.3 on 2022-12-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_main',
            name='text',
            field=models.TextField(max_length=900, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='article_main',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
