# Generated by Django 4.0.3 on 2022-12-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0002_alter_article_main_text_alter_article_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_main',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='описание'),
        ),
    ]
