# Generated by Django 4.0.3 on 2022-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0003_alter_article_main_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('text', models.TextField(max_length=2000, verbose_name='описание')),
                ('show_item', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/gallery_temporal/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Галерея новостей',
                'verbose_name_plural': 'Галерея новостей',
            },
        ),
    ]
