# Generated by Django 4.0.3 on 2022-12-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0004_gallery_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery_main',
        ),
    ]
