# Generated by Django 4.0.3 on 2023-01-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0006_gallery_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_foto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(max_length=150, verbose_name='позиция')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('text', models.TextField(max_length=2000, verbose_name='описание')),
                ('show_item', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/gallery_photo/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Галерея фото',
                'verbose_name_plural': 'Галерея фото',
            },
        ),
    ]
