# Generated by Django 4.0.3 on 2023-01-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0008_esp_kafedra_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp_kafedra_articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/kafedra_photo/profe/', verbose_name='Фото'),
        ),
    ]
