# Generated by Django 4.0.3 on 2023-01-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafedra', '0010_eng_kafedra_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='novosti_articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(max_length=150, null=True, verbose_name='позиция')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('text', models.TextField(max_length=2000, null=True, verbose_name='описание')),
                ('show_item', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/novosti/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новости - статьи',
                'verbose_name_plural': 'Новости - статьи',
            },
        ),
    ]
